name: glog
description: An implementation of glog in dart with some extra bells and whistles.
version: 1.0.1
homepage: https://github.com/farcaller/dart-glog

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  date_format: ^2.0.6
  stack_trace: ^1.10.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
